name: My First GitHub Action

on:
  push:
    branches: [main]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, this is my first GitHub Action!"

      - name: Show current date
        run: date

      - name: List files
        run: ls -la
